main: com.rayzr522.dlannouncer.DLAnnouncer
name: DLAnnouncer
version: 1.0.1
description: An announcement plugin for DoomLand Network.
author: Rayzr
commands:
  announcer:
    description: DLAnnouncer main command
    usage: "\u00a7cThe code dun failed!"
